name: "aspire-ai-chat"
services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8085:18888"
    expose:
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  pg:
    image: "docker.io/library/postgres:17.5"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "pgvolume"
        read_only: false
    networks:
      - "aspire"
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "aspire"
  chatapi:
    image: "${CHATAPI_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${CHATAPI_PORT}"
      ConnectionStrings__llm: "AccessKey=${LLM_OPENAI_API_KEY};Model=gpt-4.1;Endpoint=https://api.openai.com/v1;Provider=OpenAI"
      ConnectionStrings__conversations: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=conversations"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "chatapi"
    expose:
      - "${CHATAPI_PORT}"
    depends_on:
      pg:
        condition: "service_started"
      cache:
        condition: "service_started"
    networks:
      - "aspire"
  chatui:
    image: "${CHATUI_IMAGE}"
    environment:
      NODE_ENV: "production"
      PORT: "80"
      BACKEND_URL: "chatapi:${CHATAPI_PORT}"
      SPAN: "chatui"
      BROWSER: "none"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "chatui"
    ports:
      - "80"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  pgvolume:
    driver: "local"
